"""added Name.last_update

Revision ID: 5da76bb2b1df
Revises: 
Create Date: 2020-05-26 09:45:59.956423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da76bb2b1df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('names', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('names', 'last_updated')
    # ### end Alembic commands ###
